// <auto-generated />
using System;
using DSProject.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DSProject.Migrations
{
    [DbContext(typeof(DSBaseContext))]
    [Migration("20181001031245_NewColumnsAdded")]
    partial class NewColumnsAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DSProject.Model.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("IntegrantId");

                    b.HasKey("Id");

                    b.HasIndex("IntegrantId");

                    b.ToTable("Ability");
                });

            modelBuilder.Entity("DSProject.Model.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("IntegrantId");

                    b.HasKey("Id");

                    b.HasIndex("IntegrantId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("DSProject.Model.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("IntegrantId");

                    b.HasKey("Id");

                    b.HasIndex("IntegrantId");

                    b.ToTable("Instrument");
                });

            modelBuilder.Entity("DSProject.Model.InstrumentPlayed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("IntegrantId");

                    b.HasKey("Id");

                    b.HasIndex("IntegrantId");

                    b.ToTable("InstrumentPlayed");
                });

            modelBuilder.Entity("DSProject.Model.Integrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutCollectors");

                    b.Property<string>("Adress");

                    b.Property<string>("AdressCep");

                    b.Property<string>("AdressCity");

                    b.Property<string>("AdressDistrict");

                    b.Property<string>("AdressNumber");

                    b.Property<string>("AdressState");

                    b.Property<string>("AdvancedKnowledge");

                    b.Property<string>("BirthPlace");

                    b.Property<string>("CPF");

                    b.Property<string>("CarBrand");

                    b.Property<string>("CarColor");

                    b.Property<string>("CarModel");

                    b.Property<string>("CarOwner");

                    b.Property<string>("CarPlate");

                    b.Property<string>("CarRenavam");

                    b.Property<int>("CarYear");

                    b.Property<string>("CellPhone");

                    b.Property<string>("Company");

                    b.Property<string>("Course");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("DriverAuthorizedOne");

                    b.Property<string>("DriverAuthorizedTwo");

                    b.Property<string>("Email");

                    b.Property<string>("HourOfBirth");

                    b.Property<string>("Institution");

                    b.Property<string>("IsCollectorOfSomething");

                    b.Property<bool>("IsUseCarPlotting");

                    b.Property<bool>("IsUseCarTests");

                    b.Property<bool>("IsVoluntary");

                    b.Property<bool>("KnowStreets");

                    b.Property<string>("Name");

                    b.Property<int>("NumberOfParticipations");

                    b.Property<string>("Occupation");

                    b.Property<string>("Phone");

                    b.Property<string>("RG");

                    b.Property<DateTime>("RegistrationDate");

                    b.Property<string>("Scholarity");

                    b.Property<string>("Sign");

                    b.Property<string>("SomethingMore");

                    b.HasKey("Id");

                    b.ToTable("Integrant");
                });

            modelBuilder.Entity("DSProject.Model.Knowledge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("IntegrantId");

                    b.HasKey("Id");

                    b.HasIndex("IntegrantId");

                    b.ToTable("Knowledge");
                });

            modelBuilder.Entity("DSProject.Model.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("IntegrantId");

                    b.HasKey("Id");

                    b.HasIndex("IntegrantId");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("DSProject.Model.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("IntegrantId");

                    b.HasKey("Id");

                    b.HasIndex("IntegrantId");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("DSProject.Model.Ability", b =>
                {
                    b.HasOne("DSProject.Model.Integrant")
                        .WithMany("Abilities")
                        .HasForeignKey("IntegrantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DSProject.Model.Device", b =>
                {
                    b.HasOne("DSProject.Model.Integrant")
                        .WithMany("Devices")
                        .HasForeignKey("IntegrantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DSProject.Model.Instrument", b =>
                {
                    b.HasOne("DSProject.Model.Integrant")
                        .WithMany("Instruments")
                        .HasForeignKey("IntegrantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DSProject.Model.InstrumentPlayed", b =>
                {
                    b.HasOne("DSProject.Model.Integrant")
                        .WithMany("InstrumentPlayed")
                        .HasForeignKey("IntegrantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DSProject.Model.Knowledge", b =>
                {
                    b.HasOne("DSProject.Model.Integrant")
                        .WithMany("Knowledges")
                        .HasForeignKey("IntegrantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DSProject.Model.Language", b =>
                {
                    b.HasOne("DSProject.Model.Integrant")
                        .WithMany("Languages")
                        .HasForeignKey("IntegrantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DSProject.Model.Sport", b =>
                {
                    b.HasOne("DSProject.Model.Integrant")
                        .WithMany("Sports")
                        .HasForeignKey("IntegrantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
